pip install -r ./src/modules/certificatereader/requirements.txt
pip install -r ./src/modules/evtxreader/requirements.txt
pip install -r ./src/modules/imagerecognitiontensorflow/requirements.txt
pip install -r ./src/modules/metadata/requirements.txt
pip install -r ./src/modules/ocrtesseract/requirements.txt
pip install -r ./src/modules/pstostparser/requirements.txt
pip install -r ./src/modules/qrbcreader/requirements.txt
pip install -r ./src/modules/tikaparser/requirements.txt
pip install -r ./src/modules/windowsprefetch/requirements.txt
pip install -r ./src/modules/windowsregistry/requirements.txt
pip install -r ./src/modules/zipextractor/requirements.txt