version: '3'

services:
    opensearch:
        image: opensearchproject/opensearch:1.3.1
        env_file:
            - opensearch/opensearch/opensearch.env
        volumes:
            - opensearch-data:/usr/share/opensearch/data
        ports:
            - 9200:9200/tcp
            - 9300:9300/tcp
        networks:
            - whatthefile-net
            
    opensearch-dashboards:
        image: opensearchproject/opensearch-dashboards:1.3.1
        ports:
            - 5601:5601
        env_file:
            - opensearch/opensearch/opensearchdashboards.env
        networks:
            - whatthefile-net
   
    opensearch-config:
        image: ubuntu
        volumes:
            - ./opensearch/:/config
        environment:
            - OPENSEARCH_HOST=https://opensearch:9200
            - OPENSEARCH_AUTH=admin:admin
            - OPENSEARCH_DASHBOARDS_HOST=http://opensearch-dashboards:5601
        entrypoint:
            - bash
            - /config/entrypoint.sh
        depends_on:
            - opensearch
        networks:
            - whatthefile-net

    tika:
        image: logicalspark/docker-tikaserver
        container_name: tika
        ports:
            - 9998:9998/tcp
        networks:
            - whatthefile-net
            
    whatthefile:
        build: whatthefile
        volumes:
            - ./whatthefile/safe_directory:/safe_directory
            - ./whatthefile/input:/input
            - ./whatthefile/whatthefile.ini:/whatthefile/whatthefile.ini
            - ./whatthefile/entrypoint.sh:/whatthefile/entrypoint.sh
        container_name: whatthefile
        networks:
            - whatthefile-net
        depends_on:
            - tika
            - opensearch

networks:
  whatthefile-net:
  
volumes:
  opensearch-data:
