version: '3'

services:
    tika:
        image: logicalspark/docker-tikaserver
        container_name: tika
        ports:
            - 9998:9998/tcp
        networks:
            - tika
networks:
  tika:
