version: '3'

services:
    whatthefile:
        build: .
        volumes:
            - ./output:/output
            - ./input:/input
            - ./whatthefile.ini:/whatthefile/whatthefile.ini
            - ./entrypoint.sh:/whatthefile/entrypoint.sh
        container_name: whatthefile
        networks:
            - whatthefile
        depends_on:
            - tika
    tika:
        image: logicalspark/docker-tikaserver
        container_name: tika
        ports:
            - 9998:9998/tcp
        networks:
            - whatthefile
networks:
  whatthefile:
