name: Docker Build Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      -
    - name: Build Docker image
        run: docker build ./docker-compose/whatthefile/Dockerfile


